version: "3.7"
services:
  redis:
    image: "redis:3.2.7"

  mysql:
    image: mysql:5.7.26
    environment:
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
      - MYSQL_DATABASE=airflow
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql-cnf:/etc/mysql/conf.d

  webserver:
    build:
      context: .
    depends_on:
      - redis
      - mysql
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  flower:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    build:
      context: .
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    command: scheduler

  worker_a:
    build:
      context: .
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    command: worker

  worker_b:
    build:
      context: .
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    command: worker
