version: "3.7"
services:
  redis:
    image: "redis:3.2.7"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  webserver:
    build:
      context: .
    depends_on:
      - redis
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build:
      context: .
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    command: scheduler

  worker:
    build:
      context: .
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    command: worker
